#!/bin/bash

text_size=75
show_img=0
POSITIONAL_ARGS=()
TMP_IMAGE_FOLDER='/tmp/'
FONT='helvetica'

while [[ $# -gt 0 ]]; do
	case $1 in
		--textsize)
			text_size=$2
			shift
			shift
			;;
		--showimage)
			show_img=1
			shift
			;;
		--font)
			FONT=$2
			shift
			shift
			;;
		*)
			POSITIONAL_ARGS+=("$1")
			shift
			;;
	esac
done


make_random_name (){
	RESULT=`echo $RANDOM | md5sum | head -c 20`
	echo ${RESULT}.png
}

get_video_size () {
	ffprobe -v error -show_entries stream=width -of csv=p=0:s=x "${1}"
}

#~ -pointsize $text_size 
make_image () {
	echo $1 $2 $3 $FONT
	convert \
		-background white \
		-fill black \
		-font $FONT \
		-pointsize $text_size \
		-size $1x \
		-gravity center \
		caption:"${2}" \
		"${3}"
}

make_video (){
	echo "make_video args: "
	echo $1 $2 $3
	ffmpeg -loglevel warning -y -i "${2}" \
	-i "${1}" \
	-filter_complex \
	"[1:v]pad=iw:ih+`identify -format '%h' $2`:0:oh-ih,overlay=0:0" \
	"${3}"
}

set -- "${POSITIONAL_ARGS[@]}"
echo 'Creating image'
IMG_NAME="tmp_img_out_9483938.png"
IMG_PATH="${TMP_IMAGE_FOLDER}${IMG_NAME}"
make_image $(get_video_size "${1}") "$2" $IMG_PATH

if [[ show_img -eq 1 ]];
then
	echo 'Opening image'
	xdg-open $IMG_PATH
	echo -n "Want to continue? [Y/n]: "
	read opt
	
	if [[ $opt =~ ^[Nn]$ ]];
	then
		exit 0;
	fi
fi

echo 'Processing video...'
make_video "${1}" $IMG_PATH "${3}"

echo 'Video finished'
echo 'Deleting image'
rm $IMG_PATH
